### ISSUE TITLE
Using file_loader with watermark 

### ISSUE THREAD

**Issue by G-Kevin** [thumbor/thumbor#1124]
### Thumbor request URL
`http://thumbor:8000/unsafe/filters:watermark(folder1/file.jpg,-10,-10,70)/folder2/file.jpg`

### Expected behaviour
Both files are loaded from filesystem, watermark as overlay.

### Actual behaviour
error message:
```
thumbor_1     | 2018-10-11 14:18:04 thumbor:WARNING bad watermark result error=not_found metadata={}
thumbor_1     | 2018-10-11 14:18:04 tornado.access:WARNING 400 GET /unsafe/filters:watermark(folder1/file.jpg,-10,-10,70)/folder2/file.jpg` (172.18.0.6) 8.86ms
```

### Operating system
Hostsystem Debian 9, dockered using apsl/thumbor
Configuration:

```
  thumbor:
    image: "apsl/thumbor:6.4.2"
    ports:
      - "8000:8000"
    environment:
      - FILTERS=['thumbor.filters.watermark']
      - LOADER=thumbor.loaders.file_loader
      - FILE_LOADER_ROOT_PATH=/data/loader
    volumes:
      - ./fodler2/:/data/loader/folder1/
      - ./folder1/:/data/loader/folder2/
```

I am trying to load both watermark image and background image from filesystem. Without watermark it works fine, but as soon as I add the filters:watermark() to it, the above error occurs. I double checked that both files exist. It does not matter if I try a local image as watermark or a URL.

What is the correct way to load both watermark and background image with file_loader? Thank you!
