### ISSUE TITLE
405: Method Not Allowed

### ISSUE THREAD

**Issue by stefdaems** [thumbor/thumbor#1581]
I'm using a docker-compose.yml file to spin up my thumbor service. The docker-compose file looks like this

```
version: '3.7'
services:
  thumborimageservice:
    image: thumbororg/thumbor
    environment:
      - LOG_LEVEL=trace
      - RESULT_STORAGE=thumbor.result_storages.no_storage
      - RESULT_STORAGE_STORES_UNSAFE=True
      - UPLOAD_MAX_SIZE=5000
      - UPLOAD_ENABLED=True
      - UPLOAD_PUT_ALLOWED=True
      - UPLOAD_DELETE_ALLOWED=True
      - UPLOAD_PHOTO_STORAGE=thumbor.storages.file_storage
      - UPLOAD_DEFAULT_FILENAME=image
      - CORS_ALLOW_ORIGIN=*
    ports:
      - 8888:8888
    restart: always
```
As the UPLOAD_PUT_ALLOWED flag is set to True I would assume I am able on uploading images using the /image endpoint.
I use a small form to upload the image

```
<html>
  <head>
  </head>
  <body>
  	<form action="http://localhost:8888/image" enctype="multipart/form-data" method="post">
  	    Upload Image:
  	    <input type="file" id="media" name="media" />
  	    <input type="submit" />
  	</form> 
  </body>
</html>
```

On executing the form with a valid image I'm getting 405: Method Not Allowed returned.
