### ISSUE TITLE
404 freezes thumbor

### ISSUE THREAD

**Issue by onemorerocks** [thumbor/thumbor#697]
I'm using the following docker compose setup:

```
  thumbor:
    image: apsl/thumbor:5.2.1e
    ports:
      - "9999:8000"
    environment:
      DETECTORS: "['thumbor.detectors.face_detector','thumbor.detectors.feature_detector']"
      UPLOAD_ENABLED: 'True'
      UPLOAD_MAX_SIZE: 5242880
      UPLOAD_DELETE_ALLOWED: 'True'
```

I find after uploading an image, if I make a request to `http://192.168.99.100:9999/image/hash` it works and if I change it to `http://192.168.99.100:9999/image/badhash` I get a 404 as expected, but if I do `http://192.168.99.100:9999/unsafe/badhash` the server seems to hang for a few seconds while blocking all other requests and fails to return a proper response.

Thanks
