### ISSUE TITLE
Redis Error

### ISSUE THREAD

**Issue by Doginal** [thumbor/thumbor#936]
I am seeing some odd behaviour when running v6.3.0. The first time the image loads, I'm getting huge lag and see Redis errors for every image. Is Redis requirement for Thumbor? Is there something wrong with my config file? 
Thanks,
Doginal

### Expected behaviour
No error on image requests

### Actual behaviour
```
Stack Track:
thumbor:ERROR Redis Error
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/thumbor/detectors/queued_detector/__init__.py", line 36, in detect 
key=self.context.request.image_url
File "/usr/local/lib/python2.7/site-packages/remotecv/unique_queue.py", line 27, in enqueue_unique_from_string
if not self.add_unique_key(queue, key):
File "/usr/local/lib/python2.7/site-packages/remotecv/unique_queue.py", line 15, in add_unique_key
if self.redis.get(unique_key) == "1":
File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 880, in get
return self.execute_command('GET', name)
File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
connection.send_command(*args)
File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
self.send_packed_command(self.pack_command(*args))
File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
self.connect()
File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
raise ConnectionError(self._error_message(e))
ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
```
### Operating system
Docker

### Your thumbor.conf
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: thumbor-prod
  labels:
    app: thumbor-prod
    version: "latest"
spec:
  replicas: 1
  selector:
    app: thumbor-prod
    version: "latest"
  template:
    metadata:
      name: thumbor-prod
      labels:
        app: thumbor-prod
        version: "latest"
        role: service
        group: yourgroup
    spec:
      containers:
      - name: thumbor-prod
        image: apsl/thumbor:latest
        resources:
          limits:
            cpu: 600m
            memory: 1200Mi
          requests:
            cpu: 10m
            memory: 10Mi
        env:       
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: ALLOW_UNSAFE_URL
          value: "False"
        - name: SECURITY_KEY
          value: "MY_SECURITY_KEY"
        - name: DETECTORS
          value: "['thumbor.detectors.queued_detector.queued_complete_detector',]"
        - name: RESULT_STORAGE
          value: "tc_aws.result_storages.s3_storage"
        # - name: REDIS_STORAGE_SERVER_HOST
        #   value: redis
        # - name: REDIS_STORAGE_SERVER_PORT
        #   value: "6379"
        # - name: REDIS_STORAGE_SERVER_DB
        #   value: "11"
        # - name: REDIS_QUEUE_SERVER_HOST
        #   value: redis
        # - name: REDIS_QUEUE_SERVER_PORT
        #   value: "6379"
        # - name: REDIS_QUEUE_SERVER_DB
        #   value: "11"
        - name: STORAGE
          value: "thumbor.storages.no_storage"

        # MONGO STORAGE OPTIONS
        # - name: MONGO_STORAGE_SERVER_HOST
        #   value: mongo # MongoDB storage server host
        # - name: MONGO_STORAGE_SERVER_PORT
        #   value: '27017'
        # - name: MONGO_STORAGE_SERVER_DB
        #   value: thumbor
        # - name: MONGO_STORAGE_SERVER_COLLECTION
        #   value: images
        - name: LOADER
          value: "tc_aws.loaders.presigning_loader"
        - name: AWS_ACCESS_KEY_ID
          value: "KEY"
        - name: AWS_SECRET_ACCESS_KEY
          value: "KEYS"
        - name: TC_AWS_LOADER_BUCKET
          value: "thumbor-loader"
        - name: TC_AWS_STORAGE_BUCKET
          value: "thumbor"
        - name: TC_AWS_RESULT_STORAGE_BUCKET
          value: thumbor
        - name: TC_AWS_RESULT_STORAGE_ROOT_PATH
          value: 'staging'
        - name: TC_AWS_MAX_RETRY
          value: "0" # Max retries for get image from S3 Bucket. Default is 0
        - name: S3_USE_SIGV4
          value: "True"
        - name: TC_AWS_REGION
          value: "us-west-2"
        - name: TC_AWS_ENABLE_HTTP_LOADER
          value: "False"
        - name: THUMBOR_PORT
          value: "8001"
        - name: STORAGE_EXPIRATION_SECONDS
          value: "604800"
        - name: RESULT_STORAGE_EXPIRATION_SECONDS
          value: "604800"
        - name: RESPECT_ORIENTATION
          value: "True"
        volumeMounts:
        - name: thumbor-prod-data
          mountPath: /data
          readOnly: False
        imagePullPolicy: Always
      - name: thumbor-prod-nginx
        image: apsl/thumbor-nginx:latest
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 5Mi
        env:
        - name: THUMBOR_DEFAULT_HOST
          value: 127.0.0.1
        - name: THUMBOR_DEFAULT_PORT
          value: "8001"
        ports:
        - containerPort: 80
          name: thumbor-prod
        volumeMounts:
        - name: thumbor-prod-data
          mountPath: /data
          readOnly: True
        imagePullPolicy: Always
      volumes:
      - name: thumbor-prod-data
        hostPath:
          path: /var/thumbor-production
      restartPolicy: Always
      dnsPolicy: ClusterFirst
```
